import fs from "fs";
import path from "path";
import crypto from "crypto";

export const UPLOADS_DIR = process.env.UPLOADS_DIR || path.join(process.cwd(), "uploads");
export const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

// Preferred: a salted scrypt hash so the plaintext password never lives in the
// environment / .env file. Format: "<saltHex>:<hashHex>" where
// hashHex = scrypt(password, salt, 64). Generated by buildcdnapp/redeploycdnweb.
const ADMIN_PASSWORD_HASH = process.env.ADMIN_PASSWORD_HASH;

// Legacy: plaintext password in the environment. Still supported for backward
// compatibility, but deployments should migrate to ADMIN_PASSWORD_HASH.
export const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;

// During `next build` the route modules are imported to collect page data,
// which runs this file's top-level checks. Credentials are NOT available then
// (they're runtime-only env vars), so we must log but never hard-exit during
// the build phase — only at real server startup.
const IS_BUILD_PHASE = process.env.NEXT_PHASE === "phase-production-build";
function failStartup(...messages) {
  messages.forEach((m) => console.error(m));
  if (!IS_BUILD_PHASE) {
    process.exit(1);
  }
}

// Parse the scrypt hash once at startup.
let HASH_SALT = null;
let HASH_DIGEST = null;
if (ADMIN_PASSWORD_HASH) {
  const [saltHex, digestHex] = ADMIN_PASSWORD_HASH.split(":");
  if (saltHex && digestHex) {
    try {
      HASH_SALT = Buffer.from(saltHex, "hex");
      HASH_DIGEST = Buffer.from(digestHex, "hex");
    } catch {
      HASH_SALT = null;
      HASH_DIGEST = null;
    }
  }
}

// Security check on startup — at least one credential source is required.
if (!ADMIN_PASSWORD_HASH && !ADMIN_PASSWORD) {
  failStartup(
    "⚠️  CRITICAL: no admin credential set. Define ADMIN_PASSWORD_HASH (preferred) or ADMIN_PASSWORD.",
    "Run ./buildcdnapp or ./redeploycdnweb to generate one."
  );
}

if (ADMIN_PASSWORD_HASH && (!HASH_DIGEST || HASH_DIGEST.length === 0)) {
  failStartup("⚠️  CRITICAL: ADMIN_PASSWORD_HASH is malformed (expected '<saltHex>:<hashHex>').");
}

if (!ADMIN_PASSWORD_HASH && ADMIN_PASSWORD) {
  console.warn(
    "⚠️  WARNING: using plaintext ADMIN_PASSWORD. Prefer ADMIN_PASSWORD_HASH — re-run ./redeploycdnweb to migrate."
  );
  if (ADMIN_PASSWORD === "changeme" || ADMIN_PASSWORD === "YourSecurePassword123!@#") {
    failStartup("⚠️  CRITICAL: ADMIN_PASSWORD is still a default/example value!");
  }
  if (ADMIN_PASSWORD.length < 16) {
    console.error(
      "⚠️  WARNING: ADMIN_PASSWORD is too short (minimum 16 characters recommended)."
    );
  }
}

// Ensure uploads dir exists with secure permissions
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true, mode: 0o755 });
}

// Set secure permissions on uploads directory
try {
  fs.chmodSync(UPLOADS_DIR, 0o755);
} catch (e) {
  console.warn("Could not set directory permissions:", e.message);
}

export function listFiles() {
  return fs
    .readdirSync(UPLOADS_DIR)
    .filter((name) => {
      try {
        return fs.statSync(path.join(UPLOADS_DIR, name)).isFile();
      } catch {
        return false;
      }
    })
    .map((name) => {
      const stat = fs.statSync(path.join(UPLOADS_DIR, name));
      return {
        filename: name,
        url: `${BASE_URL}/${name}`,
        size: stat.size,
        createdAt: stat.birthtime,
        mtime: stat.mtime,
      };
    })
    .sort((a, b) => new Date(b.mtime) - new Date(a.mtime));
}

export function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9._-]/g, "").replace(/\.{2,}/g, "");
}

/**
 * Constant-time comparison of two strings of arbitrary length.
 *
 * Both inputs are first hashed with SHA-256 so the comparison operates on
 * fixed-length (32-byte) buffers — this avoids leaking the password length via
 * an early length-mismatch return, and lets us use crypto.timingSafeEqual.
 */
function constantTimeEqualStrings(a, b) {
  const ha = crypto.createHash("sha256").update(String(a)).digest();
  const hb = crypto.createHash("sha256").update(String(b)).digest();
  return crypto.timingSafeEqual(ha, hb);
}

/**
 * Verify a candidate password against the configured credential.
 * Prefers the scrypt hash; falls back to legacy plaintext comparison.
 */
function verifyPassword(candidate) {
  if (HASH_DIGEST && HASH_SALT) {
    try {
      const derived = crypto.scryptSync(candidate, HASH_SALT, HASH_DIGEST.length);
      return crypto.timingSafeEqual(derived, HASH_DIGEST);
    } catch {
      return false;
    }
  }
  if (ADMIN_PASSWORD) {
    return constantTimeEqualStrings(candidate, ADMIN_PASSWORD);
  }
  return false;
}

export function checkAuth(request) {
  const pw = request.headers.get("x-admin-password");

  if (!pw) {
    return false;
  }

  return verifyPassword(pw);
}
